<?php
/**
 * ฟังก์ชันสร้างรหัสผ่านแบบสุ่ม
 */
function randomTextSP($length = 8) {
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$*()_-+=";
    return substr(str_shuffle($chars), 0, $length);
}

/**
 * ดึงรหัสผ่าน Plaintext จาก Radius หรือสร้างใหม่หากไม่มี
 * 
 * @param string $username ชื่อผู้ใช้งาน (เช่น cid, provider_id)
 * @param string|null $email อีเมลผู้ใช้งาน (เช่น บัญชี Gmail)
 * @param string|null $fullname ชื่อ-นามสกุลจริงผู้ใช้งาน
 * @return string รหัสผ่าน Plaintext สำหรับใช้ล็อกอินเข้า FortiGate
 */
function sso_radius_auth($username, $email = null, $fullname = null) {
    $db_host = getenv('DB_HOST') ?: ($_ENV['DB_HOST'] ?? '168.148.62.15');
    $db_user = getenv('DB_USER') ?: ($_ENV['DB_USER'] ?? 'root');
    $db_pass = getenv('DB_PASS') ?: ($_ENV['DB_PASS'] ?? '');
    $db_name = getenv('DB_NAME') ?: ($_ENV['DB_NAME'] ?? 'radius');
    
    $conn = @new mysqli($db_host, $db_user, $db_pass, $db_name);
    if ($conn->connect_error) {
        error_log("Radius connection failed: " . $conn->connect_error);
        return false;
    }
    $conn->set_charset("utf8");

    // 1. ตรวจสอบว่ามี tmp_passwd ใน radcheck_mirror หรือไม่
    $stmt = $conn->prepare("SELECT tmp_passwd FROM radcheck_mirror WHERE username = ? LIMIT 1");
    $stmt->bind_param("s", $username);
    $stmt->execute();
    $result = $stmt->get_result();
    
    if ($result && $result->num_rows > 0) {
        $row = $result->fetch_assoc();
        if (!empty($row['tmp_passwd'])) {
            // ทำการอัปเดตข้อมูล email และ fullname ของผู้ใช้เก่าหากมีการเปลี่ยนแปลง
            $stmt_update_profile = $conn->prepare("UPDATE radcheck_mirror SET email = ?, fullname = ? WHERE username = ?");
            $stmt_update_profile->bind_param("sss", $email, $fullname, $username);
            $stmt_update_profile->execute();
            
            $conn->close();
            return $row['tmp_passwd'];
        }
    }
    
    // 2. หากไม่พบ หรือรหัสผ่านว่าง สร้างรหัสผ่านใหม่และอัปเดตเข้าฐานข้อมูล Radius
    $new_password = randomTextSP(8);
    $md5_password = md5($new_password);
    $attribute = "MD5-Password";
    $op = ":=";
    $date_register = date('Y-m-d H:i:s');
    $date_expire = date('Y-m-d 23:59:59'); // กำหนดหมดอายุเที่ยงคืนวันนี้
    $note = "Auto-generated by SSO Auth";
    $active = "Y";
    
    // Update หรือ Insert ในตาราง radcheck
    $stmt_check = $conn->prepare("SELECT COUNT(*) as count FROM radcheck WHERE username = ?");
    $stmt_check->bind_param("s", $username);
    $stmt_check->execute();
    $result_check = $stmt_check->get_result();
    $row_check = $result_check->fetch_assoc();
    
    if ($row_check['count'] > 0) {
        $stmt_update = $conn->prepare("UPDATE radcheck SET attribute = ?, op = ?, value = ? WHERE username = ?");
        $stmt_update->bind_param("ssss", $attribute, $op, $md5_password, $username);
        $stmt_update->execute();
    } else {
        $stmt_insert = $conn->prepare("INSERT INTO radcheck (username, attribute, op, value) VALUES (?, ?, ?, ?)");
        $stmt_insert->bind_param("ssss", $username, $attribute, $op, $md5_password);
        $stmt_insert->execute();
    }
    
    // Insert หรือ Update ในตาราง radcheck_mirror
    $stmt_mirror_check = $conn->prepare("SELECT COUNT(*) as count FROM radcheck_mirror WHERE username = ?");
    $stmt_mirror_check->bind_param("s", $username);
    $stmt_mirror_check->execute();
    $result_mirror_check = $stmt_mirror_check->get_result();
    $row_mirror_check = $result_mirror_check->fetch_assoc();
    
    if ($row_mirror_check['count'] > 0) {
        // อัปเดตข้อมูลรวมถึงอีเมลและชื่อจริง
        $stmt_mirror_update = $conn->prepare("UPDATE radcheck_mirror SET tmp_passwd = ?, attribute = ?, op = ?, value = ?, email = ?, fullname = ? WHERE username = ?");
        $stmt_mirror_update->bind_param("sssssss", $new_password, $attribute, $op, $md5_password, $email, $fullname, $username);
        $stmt_mirror_update->execute();
    } else {
        // เพิ่มข้อมูลผู้ใช้รายใหม่พร้อมอีเมลและชื่อจริง
        $stmt_mirror_insert = $conn->prepare("INSERT INTO radcheck_mirror (username, attribute, op, value, tmp_passwd, date_register, date_expire, note, active, email, fullname) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
        $stmt_mirror_insert->bind_param("sssssssssss", $username, $attribute, $op, $md5_password, $new_password, $date_register, $date_expire, $note, $active, $email, $fullname);
        $stmt_mirror_insert->execute();
    }
    
    $conn->close();
    return $new_password;
}
